service: timeslots

frameworkVersion: "3.22.0"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-offline

functions:
  getUser:
    handler: dist/modules/users/handler/UsersHandler.get
    events:
      - http:
          path: /users/{id}
          method: get
